
import __ASTRO_IMAGE_IMPORT_Z12GskI from "./images/sm1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md";
import __ASTRO_IMAGE_IMPORT_1utCzr from "./images/r2w1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md";
import __ASTRO_IMAGE_IMPORT_Z1Cwzhy from "./images/r2w2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md";
import __ASTRO_IMAGE_IMPORT_kIinI from "./images/bb1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md";
import __ASTRO_IMAGE_IMPORT_2hTekE from "./images/bb2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md";
import __ASTRO_IMAGE_IMPORT_Zd438b from "./images/orw1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md";
import __ASTRO_IMAGE_IMPORT_Z16IRWW from "./images/sb1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md";
import __ASTRO_IMAGE_IMPORT_Pr2XY from "./images/sb2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md";
import __ASTRO_IMAGE_IMPORT_Z2hz9S1 from "./images/sb3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md";
import __ASTRO_IMAGE_IMPORT_15umik from "./images/mp1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md";
import __ASTRO_IMAGE_IMPORT_Z22vPyF from "./images/mp2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md";
import __ASTRO_IMAGE_IMPORT_64aAP from "./images/mp.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md";
import __ASTRO_IMAGE_IMPORT_Z5kTBJ from "./images/mp3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md";
import __ASTRO_IMAGE_IMPORT_1QP1kc from "./images/mp4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md";
export default new Map([["./images/sm1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md", __ASTRO_IMAGE_IMPORT_Z12GskI], ["./images/r2w1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md", __ASTRO_IMAGE_IMPORT_1utCzr], ["./images/r2w2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md", __ASTRO_IMAGE_IMPORT_Z1Cwzhy], ["./images/bb1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md", __ASTRO_IMAGE_IMPORT_kIinI], ["./images/bb2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md", __ASTRO_IMAGE_IMPORT_2hTekE], ["./images/orw1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md", __ASTRO_IMAGE_IMPORT_Zd438b], ["./images/sb1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md", __ASTRO_IMAGE_IMPORT_Z16IRWW], ["./images/sb2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md", __ASTRO_IMAGE_IMPORT_Pr2XY], ["./images/sb3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md", __ASTRO_IMAGE_IMPORT_Z2hz9S1], ["./images/mp1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md", __ASTRO_IMAGE_IMPORT_15umik], ["./images/mp2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md", __ASTRO_IMAGE_IMPORT_Z22vPyF], ["./images/mp.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md", __ASTRO_IMAGE_IMPORT_64aAP], ["./images/mp3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md", __ASTRO_IMAGE_IMPORT_Z5kTBJ], ["./images/mp4.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Ffreshman2025%2FWriteUps.md", __ASTRO_IMAGE_IMPORT_1QP1kc]]);
		